### ISSUE TITLE
BUG PB

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Supra#10]
PB bug

State tidak jalan dikarenakan state function,,, harus diatur. Ada beberapa cara bisa melalui fnct_inv bisa melalui dikasi kondisi di context

Sudah dibenerin sedikit hingga state purchase,, tapi ketika kondisi barang sudah receive semua state di PB mamsih purchase seharusnya state pb line menjadi done

SHA: b4bef4507653aa74975306bb0a19017187cf011d

**Comment by lajayuhniyarsyah** [comment]
@ekachandrasetiawan mohon di benerin deadline hari ini karena besok akan di demokan di surabaya/gresik

**Comment by lajayuhniyarsyah** [comment]
@ekachandrasetiawan : sudah di revert ke script asal yang di developt

Tolong di cek,,  :  
1. State tidak jalan baik PB dari SO maupun PB dari menu Regular Requisition
2. Di cek fungsi hitung nya,, contoh: item terproses, dll....

**Comment by lajayuhniyarsyah** [comment]
Need to check
- [x] Read Only Form Order Requisition Delivery

Form Order Requisition Delivery hanya state draft saja bisa update isi form

**Comment by ekachandrasetiawan** [comment]
Sudah OK, Form hanya dapat di Edit dalam posisi Draft 

sudah di git
