### ISSUE TITLE
Quotation - User - Documentation

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Supra#107]
**Introduction**

Quotation (Penawaran) adalah dokumen yang berisikan tentang data penawaran penjualan baik barang maupun jasa kepada customer.

Pada OpenERP, modul penawaran dapat di akses pada Menu "Sales" --> "Sales" --> "RFQ"

**Comment by lajayuhniyarsyah** [comment]
**Flow**

![Flow Quotation](http://snag.gy/zdxTF.jpg)

Penjelasan Flow : 
1. Flow dimulai dengan menginput penawaran , dimana pada flow state ini form penawaran diinput oleh Sales melaui ERP pada modul menu RFQ.
2. Selanjutnya setelah inputan sudah lengkap maka user dapat mencetak penawaran di kertas dengan meng-konfirm dokumen terlebih dahulu. Pada state ini dokumen sudah fix dan tidak dapat diubah. Atau user dapat meng-cancel dokumen  tersebut jika dokumen benar-benar tidak akan digunakan
3. Selanjutnya setelah penawaran diterima oleh Customer maka akan ada proses negosiasi, dari proses tersebut ada beberapa kemungkinan yaitu **Revisi Penawaran, Deal, dan Tidak Deal / Lose**
   a. Jika ingin merevisi penawaran maka user dapat merevisi penawaran di sistem lalu mengkonfirm kembali untuk mencetak revisi penawaran
   b. Jika pada saat negosiasi menghasilkan kesepakatan Jual Beli maka ketika turun PO dari Customer user dapat mengubah status penawaran menjadi Sale Order
   c. Jika tidak ada kesepakatan atas penaran tersebut maka user dapat megubah status lose pada penawaran tersebut

**Comment by lajayuhniyarsyah** [comment]
Form

**Comment by lajayuhniyarsyah** [comment]
Case Study
1. Membuat Penawaran
2. Merevisi Penawaran
3. Deal / Turun PO
4. Cancel Quotation
5. Lose Quotation
6. Membuat Penawaran Pekerjaan include Material
7. Membuat Penawaran Penjualan Material include Pemasangan

**Comment by lajayuhniyarsyah** [comment]
F.A.Q

**Comment by ekachandrasetiawan** [comment]
Video belum dapat di buat secara sempurna
hasil record video, sudah ok dan hasil nya sudah bisa di edit untuk menghilangkan sesuatu yang tidak perlu 

tapi untuk suara belum ada

Introduction sudah ok video nya

**Comment by ekachandrasetiawan** [comment]
Video  sudah di buat dan belum di Edit 
1. Pengenalan OpenERP
2. RFQ Pengenalan
3. Pembuatan RQF 
4. Pembuatan RFQ By Product Stcok
5. Pembuatan RFQ By Product SET
6. Pembuatan RFQ Service & Barang
7. Pembuatan RFQ Barang & Service
8. Pembuatan RFQ Project (Barang & Jasa)
9. RFQ Revisi
10. RFQ Confirm & Win
11. RFQ Cancel & Lost

Video yang dibuat baru ini

**Comment by ekachandrasetiawan** [comment]
Sudah di Edit sedikit
1. Pengenalan OpenERP
2. Pembuatan RQF

**Comment by ekachandrasetiawan** [comment]
Video  sudah di  Edit 
1. Pengenalan OpenERP
2. RFQ Pengenalan
3. Pembuatan RQF 
4. Pembuatan RFQ By Product Stcok
5. Pembuatan RFQ By Product SET
6. Pembuatan RFQ Service & Barang
7. Pembuatan RFQ Barang & Service
8. Pembuatan RFQ Project (Barang & Jasa)
9. RFQ Revisi
10. RFQ Confirm & Win
11. RFQ Cancel & Lost

**Comment by lajayuhniyarsyah** [comment]
Moved to https://github.com/lajayuhniyarsyah/OpenERP-Supra-Doc
