### ISSUE TITLE
Modul Import Data Log Absen dari Mesin

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Supra#11]
SHA: 875ec658a883df6d3c5349490c1c04dfab8423fd

@Mohammadrezafah : saya udah commit inisiate modul nya,, silahkan di teruskan,,

Goal : 
- [x] Membuat view untuk upload file text

Hanya sampai buat view saja action nanti agak ribet,, saya yang terusin

**Comment by lajayuhniyarsyah** [comment]
Example file import nya

[2016-01-17_ho_log - example.txt](https://github.com/lajayuhniyarsyah/ERP-Supra/files/93815/2016-01-17_ho_log.-.example.txt)

**Comment by lajayuhniyarsyah** [comment]
untuk upload file pake fields.binary()

**Comment by lajayuhniyarsyah** [comment]
Menu nya "Import Attendance Log"

di taruh di "Human Resource" -> "Attendance"
Di taruh paling akhir

**Comment by Mohammadrezafah** [comment]
Done

**Comment by lajayuhniyarsyah** [comment]
:+1:
