### ISSUE TITLE
DN Field UOM

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Supra#112]
- [x] DN Line field uom required di xml
- [x] DN Line field product required xml
- [x] DN Material Line uom dan product required di xml
- [x] Uom dn line on change uom di allow untuk product uos nya
- [x] UOM dn line material tidak boleh onchange uom ,, uom harus sama dengan uom product
#18

**Comment by ekachandrasetiawan** [comment]
Sudah OK
