### ISSUE TITLE
Bug stock.split

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Supra#120]
- [x] Sequence no Loncat. Di testing setiap buat split baru sequence number nya ga urut,, lompat 3
- [x] Jika **stock.split.item -> qty on result == True** maka tree  stock.split.item.out qty nya di 0 kan dan di read only atau disable juga boleh. Intinya jika qty on result == True maka qty di input di akhir proses, namun jika False maka **Qty required untuk diinput**
- [x] Seperti point diatas jika qty on result == True maka qty di input di akhir proses,, qty di allow untuk input / update jika statenya "Processed"
# 
# Update
- [x] Call method validasi() ketika create(), write(), submit(). (Detail penjelasan dibawah)
- [x] Method validasi perlu penyesuaian (Detail di bawah)
- [x] Perlu validasi stock berdasarkan location, ketika submit,, perlu di cek apakah stock yang di minta untuk di split pada object stock.split.item memenuhi stock yang ada. Misal : Minta sc 2000 1 Drum, pada saat submit perlu cek sc 2000 drum ada stock nya atau ga.,, jika tidak ada stock maka return warning bahwa stock tidak ada pada location yang diminta.
#114

**Comment by lajayuhniyarsyah** [comment]
# 

# Call Method Validasi() ketika create, write dan submit

Simple,, hanya memanggil method validasi() di ketiga method tersebut

**Comment by lajayuhniyarsyah** [comment]
# 

# Method validasi perlu penyesuaian

Ini mungkin bisa jadi bahan untuk validasi

Dokumen valid jika : 
- Semua field terisi (field yang required)
- Qty tidak ada yang  0 (dikondisikan jika qty_on_result ==true maka boleh 0)
- Jika item split nya yang dipilih **Is Must Splited Into Batch No *\* == **TRUE** maka item.output harus di definisikan batch no nya
- Jika item split nya **Qty on Result** == **TRUE** maka qty Item output nya harus 0 / False

**Comment by ekachandrasetiawan** [comment]
Penyesuaian sudah OK 

Tinggal validasi nya, 
kemungkinan validasi create & Write ada sedikit penyesuaian saat mengambil value nya 

dan untuk validasi kondisi bisa di kondisikan sesuai dengan kebutuhan

**Comment by ekachandrasetiawan** [comment]
Validasi OK

Adaya validasi create, karna berbeda saat di submit
