### ISSUE TITLE
Remove unwanted package

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Supra#13]
@Mohammadrezafah : karena package _student, _kelas, _matakuliah, _nilai tidak diperlukan di sistem kita, harus di remove dari git

Step yang di perlukan di lokal reza : 
[ ] Uninstall Modul modul tersebut
[ ] Delete folder folder tersebut. (Sebelumnya silahkan di backup terlebih dahulu)
[ ] git add, commit dan push
[ ] Merge Pull Request

**Comment by Mohammadrezafah** [comment]
setelah uninstal: error AttributeError: 'NoneType' object has no attribute '_table'
![image](https://cloud.githubusercontent.com/assets/16182668/12408676/63931cfc-be95-11e5-953d-fad8e8021708.png)

**Comment by Mohammadrezafah** [comment]
Done

**Comment by lajayuhniyarsyah** [comment]
@Mohammadrezafah : error kenapa ??

**Comment by Mohammadrezafah** [comment]
udah gak error sekarang mas jay, saya uninstall lewat database nya .

**Comment by lajayuhniyarsyah** [comment]
jiah

**Comment by lajayuhniyarsyah** [comment]
yasudah,,di tempat lain belum di uninstall juga :)

**Comment by Mohammadrezafah** [comment]
sudah di remove di menu, view, module  .
apakah ada yang kurang ?

**Comment by lajayuhniyarsyah** [comment]
Udah cukup

**Comment by lajayuhniyarsyah** [comment]
issue udah closed
