### ISSUE TITLE
AP - Cash Advance Fixing Rules

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Supra#145]
Di modul PO sudah ada feature Partial Payment yang akan membentuk object invoice sebesar % payment yang akan dibuat.

Ada beberapa yang harus disesuaikan:
1. Nilai payment yang keluar adalah Total DPP (tanpa pajak) x Persentase. Saat ini yang dihitung Total Include pajak  x PPN.
2. Product yang muncul adalah product line nomor 1,, seharusnya product yang uncul adalah Advance Payment

**Comment by lajayuhniyarsyah** [comment]
Product Advance Payment

account income ke Uang Muka Penjualan 
account expense ke Uang Muka Pembelian
tipe nya service
uom = ea

**Comment by ekachandrasetiawan** [comment]
Sudah OK
