### ISSUE TITLE
Revisi PO

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Supra#152]
Untuk flow revisi

![PO Revisi](https://snag.gy/ZWeX3w.jpg)

Class Diagram

![Class Diagram](https://snag.gy/v1rw3D.jpg)

**Comment by ekachandrasetiawan** [comment]
Flow untuk melakukan revisi Po sudah OK secara flow berjalan nya
notes yang masih bermasalah adalah confirm PO 

dimana Purchase Order yang telah di confirm belum membentuk picking baru, jadi belum mendapatkan ID baru untuk melakukan proses pengecekan dan partial data dari Purchase Order yang telah di kirim dari Purhcase Order yang lama, 

Hal yang belum 
1. warning di approve PO Revision 
2. Create Log di Purchase Order 
3. Confirm PO

**Comment by lajayuhniyarsyah** [comment]
Error pada saat approve

File "/home/ekachandrasetiawan/git/ERP-Supra/sbm_po_revise/po_revise.py", line 399, in action_cancel
    val = self.browse(cr, uid, ids, context={})[0]
  File "/opt/openerp/openerp-server/openerp/osv/orm.py", line 386, in **getitem**
    raise KeyError(error_msg)
KeyError: "Field '0' does not exist in object 'browse_record(account.bank.statement, 8085)'"

**Comment by lajayuhniyarsyah** [comment]
Penambahan hal yang belum:

Hal yang belum: 
- [ ] warning di approve PO Revision
- [x] Create Log di Purchase Order
- [x] Confirm PO 
- [x] Group di button
- [x] Nama object banyak yang salah (nama function, variabel, dll) seharusnya **REVISE** bukan **RESIVE**

**Comment by lajayuhniyarsyah** [comment]
Ganti Notes ketika approval revision

Please Cancel Bank Statement MIK-0282 --> **Waiting to Cancel Bank Statement MIK-0282**

Dan kalau invoice **Waiting to Cancel Invoice {nomor nya}**

**Comment by lajayuhniyarsyah** [comment]
Notes ketika Purchasing submit untuk meminta revisi:

*_Ask for Revision with reason: {Alasan revisi}.
Waiting Approval
*_

**Comment by lajayuhniyarsyah** [comment]
Log

Purchase Order Revision Create New Purchase
menjadi
**Revision Version Created @ #nomor PO Baru**

**Comment by lajayuhniyarsyah** [comment]
Ketika Purchase.Revision menjadi **To Revise** bisa dikasih log ?
log nya **Approval to Revision Complete**

**Comment by lajayuhniyarsyah** [comment]
Pas Cofirm PO Revisi
**Revision Version Confirmed @{Nomor PO}**

**Comment by lajayuhniyarsyah** [comment]
Nama tombol PO Revision menjadi **Ask For Revision**

**Comment by lajayuhniyarsyah** [comment]
- [x] PO yang sudah ada object po.revision nya tidak boleh request po revision lagi
