### ISSUE TITLE
Bug Quotation (sales order)

### ISSUE THREAD

**Issue by Mohammadrezafah** [lajayuhniyarsyah/ERP-Supra#16]
1. Sale Item
   - Data ditak bisa di hapus
     ![image](https://cloud.githubusercontent.com/assets/16182668/12541963/864d0a96-c34f-11e5-80a7-519cfd382441.png)
   - duplicate record ketika edit dan menambahkan data
     ![image](https://cloud.githubusercontent.com/assets/16182668/12541979/c9284006-c34f-11e5-9f00-6e829a8852d3.png)
2. material item 
   - data masih ada ketika di hapus

**Comment by Mohammadrezafah** [comment]
1.sale item (problem resolved)

**Comment by lajayuhniyarsyah** [comment]
Ini sudah close ??sudah done semua ??

**Comment by Mohammadrezafah** [comment]
done semua
