### ISSUE TITLE
Nomor PO Revisi

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Supra#169]
#152

Nomor revisi tidak jadi menggunakan nomor revisi baru

Semua PO revisi menggunakan sistem nomor PO dengan kode REV

**Comment by ekachandrasetiawan** [comment]
Penyesuaian No Revise 
https://github.com/ekachandrasetiawan/ERP-Supra/commit/b54a7923e75d40259cf982290f26a258969b23b6
