### ISSUE TITLE
PO - Mail Notification When PO Revise Flow Executed

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Supra#171]
#152

Untuk memudahkan user dalam memfoloow up Revisi PO,, user butuh notifikasi

Notifikasi yang diajukan adalah by Email

Jadi untuk revisi po:
- Ketika **Ask For Revise** notifikasi by email
- Ketika **Approve** revision notifikasi ke user bahwa revisi sudah di approve
- Ketika PO sudah di create dan confirm ada notifikasi bahwa PO sudah terevisi
- dll

Jadi semua flow revisi terlihat oleh user agar dapat cepat di follow up.

**Comment by ekachandrasetiawan** [comment]
Dalam Hal ini, Fungsi Email Telah berhasil mengirimkan Email ke tujuan 
1. Membuat sesuai kebutuhan notification email
2. Memberikan Link, Doc yang di tuju
3. Subject Email

**Comment by lajayuhniyarsyah** [comment]
# Notification ON Event
1. Ketika Purchase User meminta Revisi (tombol Ask For Revision) kirim message ke Purchase Chief, Purchase Manager, Finance.
2. Ketika Finance/Purchase Chief approval revisi, kirim notifikasi ke purchase user
3. Ketika Purchase Order Revsii baru di confirm kirim message ke purchase chief, manager dan finance bahwa PO sudah di revisi dan di confirm
