### ISSUE TITLE
Tombol Work Order di SO

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Supra#190]
User butuh tombol _Generate WO_\* pada object **Sales Order**

Tujuannya memudah kan user admin support untuk Generate WO tanpa pergi ke menu SBM Work Order

**Comment by ekachandrasetiawan** [comment]
Dalam Create Work Order Dari generare Sales Order ada beberapa field yang harus di isi 
1. Work Location 
2. Internal Handler Location

dalam hal ini, di isi dari data sale order yang mana ?

**Comment by lajayuhniyarsyah** [comment]
Itu field nya required

field tersebut required nya di ubah jadi false (tidak required) namun pada object sbm_work_order pada view xml nya field tersebut required

Jadi required dari view,, bukan required dari Model.

**Comment by ekachandrasetiawan** [comment]
OK 
Salah commit 
https://github.com/ekachandrasetiawan/ERP-Supra/commit/4997217f261d517e2ae28d416610b596a6eff7b7

**Comment by lajayuhniyarsyah** [comment]
Kalau dilihat dari source nya ketika create belum redirect ke WO nya

Bikinin ketika create selesai tampilan di redirect ke wo yang tercreate
