### ISSUE TITLE
Email notification - OP

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Supra#193]
On State == Submit:
- Email notifikasi (dikirm kepada warehouse user) bahwa ada OP yang harus di proses

On State == "Done"
- Email notifikasi (dikirim kepada followers OP selain Warehouse User) bahwa OP telah di validate dan siap untuk dijadikan surat jalan

**Comment by lajayuhniyarsyah** [comment]
Status terakhir gimana can ???
Hari ini mau meeting lagi

**Comment by ekachandrasetiawan** [comment]
Status Terakhir dari checkbox widget, tidak ada pengaruh yang ditemukan 
dari xml yang membentuk itu 
dia hanya widget.comment saja, yang dibentuk dari file .js mail mail 

jadi harus menggunakan send email script, 
send email script sudah di buat di object order preparation, tapi masih ada beberapa kendala error, 
karna dia membentuk object mail baru dikirim

**Comment by ekachandrasetiawan** [comment]
isi dari Email yang akan di kirim ke team warehouse dan team admin, format nya seperti apa ?
Agar di sesuai dengan kebutuhan

**Comment by lajayuhniyarsyah** [comment]
Message ketika OP di submit

```
Dear {Username gudang/TO}

{Username submiter} telah mensubmit OP {Nomor OP}
Klik link ini untuk melihat Dokumen
```

**Comment by lajayuhniyarsyah** [comment]
Message ketika OP di validate

```
Dear {Admin HO username/ pembuat dokumen}

{Username validate} telah memproses OP {Nomor OP} dan siap untuk dibuatkan surat jalan / Delivery Notes
Klik link ini untuk melihat dokumen.
```
