### ISSUE TITLE
Refresh DN No

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Supra#198]
Team Admin HO menginginkan ada feature untuk mengupdate no DN yang berstatus postpone dan akan di proses lebih lanjut.
Alasannya, contoh:
- DN 160043C/SBM-ADM/JH-RL/IV/16
- DN tersebut diatas di postpone hingga 1  Bulan,, bulan berikut nya baru dikirim
- Nomor DN tersebut dapat dipakai namun bulannya tidak valid,, seharusnya bulan V (Lima)
- 160043C/SBM-ADM/JH-RL/V/16

Suggest nya lebih baik dibikin tombol untuk refresh bulan dan tahun dari nomor dokumen.
Lebih baik lalgi jika nomor DN dipisah dengan kode kode lainnya.

Open Disscusss

**Comment by ekachandrasetiawan** [comment]
Dalam hal ini apakah hanya bulan dan tahun saja yang berubah? atau semuanya.. 

jika no urut nya tidak berubah, mungkin kita bisa bikin konsep no seperti work order yang baru, 
dimana no urut dan seq_no dipisahkan dengan function 

Jadi Kita merubah dengan button untuk mengupdate field function tersebut

atau kita bisa membuat button langsung mengambil seq terbaru saat melakukan proses generate no

**Comment by lajayuhniyarsyah** [comment]
Jadi nomor tetap,, Bulan dan tahun ada refreshment

Iya lebih baik seperti itu,,, jadi benar benar field nomor untuk nomor saja,, field kode, bulan dan lain lain di pisah,,, nanti disatuin pada field function

**Comment by ekachandrasetiawan** [comment]
OK

Sebaiknya saya update di module apa yaa ?

**Comment by lajayuhniyarsyah** [comment]
tetap di sbm_order_handler/sbm_delivery_note

**Comment by lajayuhniyarsyah** [comment]
Pull request dulu
