### ISSUE TITLE
Purchase Order - Waiting Approval

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Supra#200]
Sort  pada menu modul Waiting Approval PO Local saat ini adalah di sorting berdasarkan nomor PO paling baru.

Menurut user Ibu Suci sorting lebih baik secara DESC.
Artinya nomor PO baru muncul di bawah yang paling atas adalah nomor PO waiting approve yang paling tua/lama

**Comment by ekachandrasetiawan** [comment]
Tidak bisa di sort by xml, 

kalo menggunakan sort by python dari object purchase.order maka akan di sort juga di menu purchase order

Ada cara lain untuk menghandle ini?

**Comment by lajayuhniyarsyah** [comment]
close ya,,, read caranya di commit ref diatas

**Comment by ekachandrasetiawan** [comment]
Alhamdllah 

Ok Thanks
