### ISSUE TITLE
PO Revisi - Discount disabled

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Supra#205]
PO 162525/PO/SBM/VIII/16/Rev1 adalah PO revisi

Ketika user ingin merivisi discount tidak bisa karena readonly

Sementara itu ketika di test di Data lain (PO yang masih draft) discount tidak disable/readonly

Pleas check and fix

**Comment by ekachandrasetiawan** [comment]
Field Discount Disable karna status dari Order Line berstatus bukan Draft, Jadi merubah state saat create Purchase Order revisi semua status LINE menjadi draft
