### ISSUE TITLE
Perubahan Account Cominco

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Supra#207]
Di Email sudah di sertakan deskripsi pekerjaannya.

**Comment by lajayuhniyarsyah** [comment]
Untuk G2 masuk ke account Penjualan Product Surface (211200) dengan sales Pak Soesanto (GM)

**Comment by ekachandrasetiawan** [comment]
DONE

**Comment by ekachandrasetiawan** [comment]
SALES ORDER Merubah Group & Sales Person DONE
