### ISSUE TITLE
Purchase Order  Status Waiting Dapat Melakukan Print Out

### ISSUE THREAD

**Issue by ekachandrasetiawan** [lajayuhniyarsyah/ERP-Supra#215]
Ada keluhan dari Finance, purchase order Status Waiting Bagian Purchase dapat melakukan print out, tanpa ada status di document nya

apakah ingin button print nya di hilangkan saat status waiting, atau doc print out nya dikasih status waiting

**Comment by ekachandrasetiawan** [comment]
@lajayuhniyarsyah  Mohon arahanya

**Comment by lajayuhniyarsyah** [comment]
Harus ditanyakan dulu masalah nya apa ?? Alasan nya apa tidak boleh melakukan print out di waiting approval ??

**Comment by lajayuhniyarsyah** [comment]
Pada saat staff mengconfirm PO yang masih draft maka status po menjadi "Waiting Approval" dan staff dapat memprint PO (resmi) yang dapat di ajukan untuk ditandatangani/di approve oleh manager untuk di kirim ke Supplier.

Sementara itu pada Draft staff dapat memprint namun terdapat Watermark "Draft",
Dan pada PO bersattus Approved maka akan ada Watermark "Approved"

Kenapa pada saat waiting approval tidak ada Watermark itu menandakan Print Out PO tersebut (Jika sudah di tandatangani oleh manager maka dapat di release ke Supplier / Print Out PPO resmi yang dapat direlease ke external Supra.

**Comment by ekachandrasetiawan** [comment]
Jadi masalah di bu maya, status PO saat mau di jornal atau di proses doc finance selanjutnya tidak dapat di proses dikarnakan status PO yang masih waiting, sedangkan doc PO sudah diterima 

jadi ada proses pending status di system

**Comment by lajayuhniyarsyah** [comment]
Kalau begitu itu karena kesalahan User dalam hal ini Manager Purchasing

Pada flow yang sudah di release dan disepakati bahwa Print out yang di hasilkan Oleh sistem adalah print out resmi yang belum di setujui, pada proses ini staff akan memprint out lalu mengajukan kepada Manager Purrchasing untuk di tanda tangani baik secara manual (tnda tangan basah) maupun sistem,, 

Jadi yang dikeluhkan finance adalah karena kesalahan user yang tidak menjalankan Sistem yang sudah di sepakati,,, confirm->print->approve (tinta & sistem)->proses dan yang dilakukan hanya approval manual (tanda tangan basah saja) tanpa approval di sistem, sehingga menghambat finance untuk memproses dokumen.

**Comment by ekachandrasetiawan** [comment]
OK
