### ISSUE TITLE
PN non ASCII

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Supra#217]
PN admin Non Asci bisa dilihat pada query berikut ini:

``` sql
SELECT pp.id, pp.default_code, pp.name_template from product_template pt
JOIN product_product pp ON pp.product_tmpl_id = pt.id
WHERE pt.id in (
    SELECT product_tmpl_id FROM product_product
    WHERE NOT name_template ~ ( '^('||
     $$[\09\0A\0D\x20-\x7E]|$$||               -- ASCII
     $$[\xC2-\xDF][\x80-\xBF]|$$||             -- non-overlong 2-byte
      $$\xE0[\xA0-\xBF][\x80-\xBF]|$$||        -- excluding overlongs
     $$[\xE1-\xEC\xEE\xEF][\x80-\xBF]{2}|$$||  -- straight 3-byte
      $$\xED[\x80-\x9F][\x80-\xBF]|$$||        -- excluding surrogates
      $$\xF0[\x90-\xBF][\x80-\xBF]{2}|$$||     -- planes 1-3
     $$[\xF1-\xF3][\x80-\xBF]{3}|$$||          -- planes 4-15
      $$\xF4[\x80-\x8F][\x80-\xBF]{2}$$||      -- plane 16
     ')*$' ) and product_product.active
)
 is true and pt.sale_ok is true
```

Untuk yang ada simbol seperti (DIameter), 3/4, m2, dll akan diserahkan ke admin (Novri) untuk di rewrite ulang,,

Untuk yang non simbol,, mohon di cek di notepad++,, ganti encoding nya maka akan terlihat bagian mana saja yang ada non character ascii nya, lalu di rewrite ulang,,

**Comment by lajayuhniyarsyah** [comment]
@ekachandrasetiawan ,, tolong dipisah mana yang ada simbol mana yang enggak ada

Yang ada simbol di listing di excel,, untuk nanti dikasih ke Novri

Yang ga ada simbol (Artinya ada character asing yang tidak terlihat) bisa di cek di notepad lalu rewrite.

**Comment by ekachandrasetiawan** [comment]
Product Telah Selesai di sesuaikan, dimana melakukan proses pengecekan ulang secara keseluruhan product yang memiliki kode ASCII, jadi dari *spasi, - , / *
dan setelah di query sudah tidak ada yang muncul kembali setelah dirapihkan

hanya product yang bener bener menggunakan symbol Ø , ¾, m², 45º, ½, ",
