### ISSUE TITLE
Modify Quotation Submited

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Supra#227]
Flow pada sbm_order_handler untuk pembuatan quotation adalah

Draft->Submit->Win / Lose / Cancel

Management mengininkan yang mengconfirm untuk menjadi SO (WIN) di sistem adalah Admin Support

Jadi yang dapat mengklik tombol WIN adalah User yang terdefinisi sebagai "Admin Support"

Jadi pada saat status submit,, user Admin Support dapat mengedit quotation, namun user sales tidak dapat edit so.
Selain itu sama seperti sebelumnya Admin Support dapat mengopen untuk revisi, cancel, dll.

NOtes:
- Karena Admin HO dapat membuat SO juga mohon dipastikan admin ho juga dapat membuat, submit, win

**Comment by ekachandrasetiawan** [comment]
untuk Admin Support yang dapat mengedit saat status submit, saya belum dapat menemui cara dari xml nya.
karna dalam hal ini, ada kondisi dimana readonly pada status submit & group admin support 

kemungkinan untuk masalah ini, akan dilakukan cara untuk membedakan akses saja, antara sales supra, dan admin support

**Comment by ekachandrasetiawan** [comment]
Pakai Metoder Read di field .py nya tidak berjalan juga, 
Referensi 
http://stackoverflow.com/questions/18912997/how-to-make-field-readonly-based-on-group-and-status

Kemungkinan, akses akan saya buat dengan membatasi di def write saja
