### ISSUE TITLE
Whitespace PO name

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Supra#247]
Tambahkan fungsi pada saat update nomor PO
di bersihin agar  tidak ada SPasi di awal atau di akhir

Lalu di cek format awal nya sudah ada atau belum,,

contoh user menginput 163674/PO/SBM/X/16

Nah sistem langsung cek 163674 sudah ada belum di sistem (cek nomor awal saja)

**Comment by ekachandrasetiawan** [comment]
Baik nya di module apa ya?
