### ISSUE TITLE
Bug OP tarik SO

### ISSUE THREAD

**Issue by Mohammadrezafah** [lajayuhniyarsyah/ERP-Supra#25]
bug ketika ngambil so 

![image](https://cloud.githubusercontent.com/assets/16182668/12837064/5ec99b9c-cbf1-11e5-8e0b-f26d67aacf38.png)

**Comment by lajayuhniyarsyah** [comment]
@ekachandrasetiawan : actor "admin ho" dikasih access right aja ke sale.order.material.line akses nya read, create, write

**Comment by ekachandrasetiawan** [comment]
Penambahan Access Rules untuk Admin HO atau object sale order material line

https://github.com/ekachandrasetiawan/ERP-Supra/commit/c092ab9a6b48e2672ed867e194a9a0d4809c0a97

**Comment by lajayuhniyarsyah** [comment]
Pull Request can
