### ISSUE TITLE
Posisi Letak Field SO dan RFQ

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Supra#252]
RFQ pure menggunakan view form baru (write ulang)

Sedangkan sale order masih menggunakan view lama (hanya penambahan material)

Perlu penyamaan agar user tidak bingung

Pada gambar dibawah (Posisi Field Payment Term ada di bawah page)
![IMg](https://snag.gy/mao41Q.jpg)

__Pada gambar berikut nya tampilan Term Payment ada di Tab__

![Img sale order](https://snag.gy/THiayZ.jpg)

**Comment by ekachandrasetiawan** [comment]
Ref 
https://github.com/ekachandrasetiawan/ERP-Supra/commit/a1e49d2d766e1df8c9f6020bebcc90346254959c
