### ISSUE TITLE
Bug Button Posphone Delivery Note

### ISSUE THREAD

**Issue by Mohammadrezafah** [lajayuhniyarsyah/ERP-Supra#26]
pada saat state approve pada data lama klik button posphone 
![image](https://cloud.githubusercontent.com/assets/16182668/12837207/c6b4283e-cbf2-11e5-97b5-2b9d636540ea.png)
- [ ] Bug Validate DN Lama: https://github.com/lajayuhniyarsyah/ERP-Supra/issues/26#issuecomment-182787347

**Comment by lajayuhniyarsyah** [comment]
@ekachandrasetiawan : yang dimaksud @Mohammadrezafah ketika data lama "yang sudah approve" di klik postpone akan muncul error seperti itu.

Hal tersebut sangat akan terjadi jadi harus di antisipasi by system minimal dengan mengeluarkan warning ke user agar user tahu apa yang harus diperbuat.

**Comment by ekachandrasetiawan** [comment]
untuk button postpone di DN mencoba mengecek, beberapa kondisi 

dimana jika kondisi picking_id di OP ada dan picking_id di DN ada maka di allow untuk postpone nya.

dan jika picking id di OP ada dan picking_id di dn tidak ada maka tampilkan warning

**Comment by lajayuhniyarsyah** [comment]
ref commit nya @ekachandrasetiawan

**Comment by lajayuhniyarsyah** [comment]
@ekachandrasetiawan : 

Ada case ketika data DN lama ber status "Approve" di klik tombol validate,, 
Yang terjadi status berubah jadi done,, seharusnya muncul error tidak bisa di validate dikarenakan di DN lama tidak ada picking

Acuannya picking karena pada saat validate ada action untuk merubah state picking jadi done

**Comment by lajayuhniyarsyah** [comment]
@ekachandrasetiawan : Koreksi

Ternyata flow nya jika tidak ada picking maka menggunakan flow lama

Di ubah sedikit aja,, jadi ketika tidak ada picking silahkan gunakan flow lama tapi picking_id di OP harus di copy ke DN

``` python
def package_new_validate(self, cr, uid, ids, context=None):
        val = self.browse(cr, uid, ids, context={})[0]
        if val.picking_id.id:
            stock_picking = self.pool.get('stock.picking')
            stock_move = self.pool.get('stock.move')
            partial_data = {}
            move = self.pool.get('stock.move').search(cr, uid, [('picking_id', '=', val.picking_id.id)])
            data_move = self.pool.get('stock.move').browse(cr, uid, move)
            # Update Done Picking & Move
            stock_picking.action_move(cr, uid, [val.picking_id.id])

            self.write(cr, uid, ids, {'state': 'done'})
        else:
            self.pool.get('delivery.note').package_validate(cr, uid, ids)
        return True

```

dikasih di kondisi else **copypicking_id yang ada di order_preparation ke delivery.note**
