### ISSUE TITLE
Group User External HO

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Supra#268]
DI sistem perlu didefinisikan apakah user ho atau bukan

Tujuannya untuk memprin print out dari PHP server yang ada di HO

Task:
- Buat Group "Using Public IP Address" ada kelompok group "Others"
- Buat system parameter dengan name "base.print.public" dengan nilai http://110.232.89.202:10002/OpenPrint/web/index.php?r=
- Semua action print di tambahkan kondisi,, jika user termasuk dalam group "Using Public IP Address" maka print redirect ke base.print.public

**Comment by lajayuhniyarsyah** [comment]
Group "**Using Public IP Address**" ditaro di kelompok group ini

![Img others](https://snag.gy/CLo5JH.jpg)

**Comment by ekachandrasetiawan** [comment]
Sebaiknya di buat di module apa ?
Apakah menggunakan setting System Parameter lagi untuk mendefinisikan link nya atau manual

**Comment by lajayuhniyarsyah** [comment]
module baru aja

sbm_user

Link nya tetap di definisiin di system parameter,, biar bisa update tanpa rubah script
