### ISSUE TITLE
Modul Log Absensi

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Supra#27]
@Mohammadrezafah : 

Perlu ada modul lihat log absensi di menu

Di modul saat ini ada menu "Machine Log" di modul "Human Resource"

Rename menu tersebut jadi "Attendance Log"

Lalu apply use case dibawah ini:
![Image of use cas attendance Log](http://snag.gy/BSOOt.jpg)

use Case Description : 
- User yang terdaftar dalam group "Employee" hanya bisa melihat data absensi nya sendiri,, tidak dapat melihat data absensi orang lain.
- User yang terdaftar sebagai HR staff dan Manager dapat melihat seluruh log absensi

**Comment by lajayuhniyarsyah** [comment]
@Mohammadrezafah : Please rapihin tree nya,,
- [x] kasih tree hanya log_time, employee_id saja

**Comment by Mohammadrezafah** [comment]
Done
