### ISSUE TITLE
Order Receive Status

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Supra#271]
**Order Receive Status** adalah menu untuk melihat status receiving item dari menu tersebut dapat diketahui berapa item yang di pesan dan berapa item yang sudah di terma oleh gudang.

Untuk memaksimalkan fungsi analisa bagi purchasing dan gudang perlu penambahan fitur-fitur:

1. User dapat mengetahui Item mana saja dari po mana saja yang masih belum complete receive
2. User dapat mengetahui item mana saja dari po mana saja yang sudahd lewat batas tanggal namun belum complete
3. User dapat mengetahui item mana saja yang harus di receive hari ini (batas waktu pengiriman hari ini)

**Comment by ekachandrasetiawan** [comment]
**Kondisi ::**
1. User dapat mengetahui Item mana saja dari po mana saja yang masih belum complete receive, 
    Dimana Kondisi di sini menjelaskan bahwa Barang belum diterima tapi masih dalam jangka waktu data planned
2. User dapat mengetahui item mana saja dari po mana saja yang sudahd lewat batas tanggal namun belum complete
   Dimana Kondisi barang belum diterima perhari ini,
3. User dapat mengetahui item mana saja yang harus di receive hari ini (batas waktu pengiriman hari ini)
Sudah OK

**Comment by lajayuhniyarsyah** [comment]
Ga jalan ya can,,

semua nya received nya 0

![img](https://snag.gy/8ZYAlv.jpg)
