### ISSUE TITLE
PB SPK

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Supra#295]
Pada sbm_work_order

Butuh modul untuk menggenerate PB dari item SPK, ,baik dari item output maupun itemraw material.

Class detail.pb:
- wo_item_output_id = many2one(sbm.work.order.output, string="For Supply WO Output")
- wo_item_output_material_id = many2one(sbm.work.order.output.raw.material, string="For Supply WO Raw Material")

class sbm.work.order.ourput.raw.material:
- regular_requisition_item_id: many2one(detail.pb, string="Requisition Item")

Cara user pick up PB ada 2
1. Pilih berdasarkan item raw material yang sudah di definisikan
2. Pilih berdasarkan item output,, jika user memilih berdasarkan item output maka item raw material akan terbentuk otomatis berdasarkan PB

**Comment by lajayuhniyarsyah** [comment]
Perbaikan 1

![image](https://cloud.githubusercontent.com/assets/6639871/21306234/9372503a-c602-11e6-962b-e52217803707.png)

**Comment by lajayuhniyarsyah** [comment]
Perbaikan 2

![image](https://cloud.githubusercontent.com/assets/6639871/21306326/f9b900e6-c602-11e6-896b-965d86adf3b4.png)

**Comment by ekachandrasetiawan** [comment]
untuk Membuat PB sudah OK, sudah dapat disesuaikan dari mana mengambil barangnya

tingal, membentuk Raw material dari Output yang dipilih saat Confirm PB

**Comment by lajayuhniyarsyah** [comment]
Untuk Source Location nya default nya HO,, id xml nya stock.stock_location_stock

**Comment by lajayuhniyarsyah** [comment]
Untuk model  detail.pb __sale_order_material_line__ , __sale_line_ids__ mohon diisi jika memang ada relasinya.
