### ISSUE TITLE
Sale Order Material Line - ON Change Product ID

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Supra#307]
1. Tambahkan fitur pada on change product_id, 
    jika prouct yang dipilih ada bom nya maka di reset dan diberi alert "__Product Set Harus Dijabarkan__"

**Comment by lajayuhniyarsyah** [comment]
@ekachandrasetiawan ,, nanti tolong langsung di upload ke server,, thanks

**Comment by ekachandrasetiawan** [comment]
ini di Objet Apa jay ?
