### ISSUE TITLE
Internal Move - Return

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Supra#312]
Perlu ada internal move wizard untuk membuat return internal move

Ada tombol pada saat status "done"

- Tombol nya wizard untuk item mana saja yang akan di return
- ketika wizard di submit membentuk data internal move baru

Class Model:

internal_move
- return_ref_id: many2one(internal_move, not required)

internal_move_line
-return_line_ref_id: many2one(internal_move_line_id, not required)

**Comment by ekachandrasetiawan** [comment]
dalam internal move, ada status
Transfer (Transfer) & Received (Done)

Apakah tetap di DONE, karna dari banyak doc Internal Move saat ini baru 6 yang benar - banar Received (Done)

Dan apakah perlu buat module baru atau di sbm_inherit saja

**Comment by lajayuhniyarsyah** [comment]
iya di done,, karena modul return harus di receive dulu,,
Ini untuk site yang receive


di sbm_inherit aja.
