### ISSUE TITLE
Schedule Date PO Item

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Supra#314]
Schedule date po item harusnya mengikuti due date bukan order date.

![image](https://cloud.githubusercontent.com/assets/6639871/21490769/12de75e2-cc2a-11e6-8388-4ad87d114831.png)

**Comment by lajayuhniyarsyah** [comment]
![image](https://cloud.githubusercontent.com/assets/6639871/21534838/7f80cc92-cd9f-11e6-9e50-b6534edc62f1.png)

**Comment by ekachandrasetiawan** [comment]
DONE
