### ISSUE TITLE
Tombol Copy PO

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Supra#315]
Perlu action untuk mencopy isi PO
Untuk repeat order (sama seperti SO)

Rules nya:
- ketika copy di cek ,, pn nya harus aktif, jika ada pn tidak aktif copy po dibatalkan (exception)

**Comment by lajayuhniyarsyah** [comment]
Di Revisi lagi,, disamain sama SO,, jika di copy nilai nya kosong,,

**Comment by ekachandrasetiawan** [comment]
DONE
