### ISSUE TITLE
Revisi Internal Move - 1

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Supra#318]
- Perlu vaidasi qty,, jumlah yang di return tidak boleh melebihi jumlah yang dikirim
- Jumlah __TOTAL__ qty yang sudah pernah di return tidak boleh melebihi jumlah yang dikirim.

**Comment by lajayuhniyarsyah** [comment]
![image](https://cloud.githubusercontent.com/assets/6639871/21535060/978c4084-cda2-11e6-86cc-95a929befeea.png)

Script validasinya malah di komen ??always true

![image](https://cloud.githubusercontent.com/assets/6639871/21535133/5dc7ea46-cda3-11e6-9a49-4135ce342bde.png)

**Comment by ekachandrasetiawan** [comment]
DONE
