### ISSUE TITLE
Nomor sequence PO Padding, Suffix, dan Prefix

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Supra#321]
Nomor sequence PO 2 digit pertama itu tahun

Jangan jadi value sequence tapi biar otomatis dari sistem aja

![image](https://cloud.githubusercontent.com/assets/6639871/21512007/917cb0c0-ccda-11e6-8b92-9e10c3fb441b.png)

Seharusnya begini bisa

![image](https://cloud.githubusercontent.com/assets/6639871/21512037/e3564064-ccda-11e6-8846-12f2d7f80677.png)

Tinggal tambahin suffix di python untuk generate angka romawi bulan dan tahun "__/XII/16__"

**Comment by ekachandrasetiawan** [comment]
Setelah di Coba  dan di cari di Ref, dari yang pernah dibuat dan di cari ref luar, 
saya belum bisa mengabungkan  seq dari suffix dan prefix 

saat pengambilan seq, ada warning invalid suffix dan prefix
Tapi untuk yang sebelumnya bisa, hanya di sesuaikan depannya saja.
