### ISSUE TITLE
Return DN (to be refund) tidak bisa tarik dari OP lagi

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Supra#33]
Saat  ini saat OP ditarik dari SO akan mengecek nilai sisa dari OP yang sudah DONE.

Bug terjadi jika DN di retur dan akan di kirim barang penggantinya

Pada OP tidak bisa menarik SO item lagi dikarenakan stattus nya sudah clear jumlah item yang sudah jadi OP

Yang harus dilakukan 
- [x] Di DN Line ada field **refunded_item** dimana untuk flag berapa qty barang yang sudah di retur namun di modul baru field ini tidak berfungsi dikarenakan yang di retur adalah item yang ada di dn.line.material. Copy field ini ke dn.material.line **dengan nama refunded_item_qty**
- [x] Pastikan fields refunded_item_qty jalan ketika return dan terisi sesuai jumlah qty yang sudah di retur
- [x] Di DN Line ada op_line_id dimana field ini tidak akan terpakai jiuka diimplementasikan dengan module update ini,, **op_line_id seharusnya ada di dn.line.material**
- [x] Pastikan op_line_id di dn.line.material terisi jika di save datanya
- [x] Di OP line ada field **dn_line_material** dimana bertipe one2many ke dn.line.material,, gunanya untuk link object saja (untuk pengecekan ke object dn yang sudah terbentuk)
- [x] Ketika field field di atas sudah diisi maka method **sale_change()** jumlah qty sisa bisa dikondisikan ditambah refunded_item yang ada di dn.line.material dengan cara akses via field **dn_line_material** yang ada di op

Class DN di package sbm_delivery_note:
![Image of class DN](http://snag.gy/BvBoS.jpg)

ada masukkan @ekachandrasetiawan ??

**Comment by lajayuhniyarsyah** [comment]
@ekachandrasetiawan : class diagram nya udah di update ya,, dn_line_material_id di object op udah di package sbm_delivery_note

dan ada object delivery_note_line_material_return

**Comment by ekachandrasetiawan** [comment]
Penyesuaian 
On Change Location 
dan Confirm OP 

Maaf tadi lupa memberikan tanda pada saat commit

File Git 
https://github.com/ekachandrasetiawan/ERP-Supra/commit/b4efbd9a0b0336e83f68638a51d8d30a98529938

**Comment by lajayuhniyarsyah** [comment]
@ekachandrasetiawan :

Please ganti nama field nya sesuai class diagram dan point diatas

Berikut quote diatas

> - [ ] Di DN Line ada field refunded_item dimana untuk flag berapa qty barang yang sudah di retur namun di modul baru field ini tidak berfungsi dikarenakan yang di retur adalah item yang ada di dn.line.material. Copy field ini ke dn.material.line dengan nama refunded_item_qty

``` python
'refunded_item': fields.function(_get_refunded_item, string='Refunded Item', store=False),
```

**Ganti** jadi **refunded_item_qty**

**Comment by lajayuhniyarsyah** [comment]
@ekachandrasetiawan : 

ini juga coppy paste

``` python

def _get_refunded_item(self,cr,uid,ids,field_name,arg,context={}):
        res = {}
        for item in self.browse(cr,uid,ids,context=context):
            refunded_total = 0
            for refund in item.note_line_material_return_ids:
                refunded_total += refund.product_qty

            if item.qty == refunded_total:
                self.write(cr,uid,[item.id],{'state':'donerefund'})
            res[item.id] = refunded_total
        return res

```

itu ada function state = donerefund

**Comment by lajayuhniyarsyah** [comment]
di pull lagi ya

**Comment by lajayuhniyarsyah** [comment]
8f7f6bb9bb2b9e80f45777a69463c5fd5885daa7

**Comment by ekachandrasetiawan** [comment]
OK
