### ISSUE TITLE
PO Line IDS pada Detail.PB

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Supra#331]
![image](https://cloud.githubusercontent.com/assets/6639871/21601529/38df30ee-d1be-11e6-9de2-a7d425439ea0.png)

Tambahin field one2many ke purchase.order.line
Biar bisa terlihat item pb nya di buat ke PO mana aja,,
Field2 nya:
 - No PO
 - Qty
 - Received Qty

**Comment by lajayuhniyarsyah** [comment]
Field yang menjadi foreign key antara detail.pb dan purchase.order.line adalah line_pb_general_id

Sementara field tersebut di buat pada sbm_purchaseorder maka inherit class detail.pb harus ada di modul sbm_purchaseorder

![image](https://cloud.githubusercontent.com/assets/6639871/21601616/f5814278-d1be-11e6-95b8-a21be1d9a242.png)

**Comment by ekachandrasetiawan** [comment]
DONE
