### ISSUE TITLE
PO Not Applicable

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Supra#378]
Banyak stock picking not applicable
dicari masalahnya kenapa

Jika ada yg bisa di handle dari flow ya penyelesaiannya dari flow  aja

Terakhir di override jadi 2binvoiced

**Comment by ekachandrasetiawan** [comment]
git 
https://github.com/ekachandrasetiawan/ERP-Supra/commit/533c2ad14a3b6f47c5a0e111f00da072c6654b1a

**Comment by lajayuhniyarsyah** [comment]
di pull request,, upload dan restart server ya @ekachandrasetiawan
