### ISSUE TITLE
Delivery Note Line Attribute - State

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Supra#39]
#18

Di DN line ada field **state**

fungsinya untuk apa ya ??

dilihat flow nya ga jalan,, ada field di database tapi ga nyimpen apa2

**Comment by lajayuhniyarsyah** [comment]
@ekachandrasetiawan : fields state di jadiin related ke field state delivery note aja,, udah ga dipakai kan ??

**Comment by ekachandrasetiawan** [comment]
OK  sudah di sesuaikan

**Comment by lajayuhniyarsyah** [comment]
:+1:

**Comment by lajayuhniyarsyah** [comment]
@ekachandrasetiawan : baru ngeh,,, field "**desc**" diubah menjadi "**name**"  :confused: 
ubah lagi

**Comment by lajayuhniyarsyah** [comment]
pakai _rec_name = 'product_id'
