### ISSUE TITLE
sale_change dan loc_change

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Supra#42]
Di sbm_order_preparation.py 

di commit 43d7db67d3b84d88832ac0c86aa386bc29b664a8
ada def sale_change dan loc_change
fungsinya mirip beda domain aja

Seharusnya bisa jadi satu,, biar ga boros script

**Comment by ekachandrasetiawan** [comment]
Kalo di gabung ada error yang nga bisa tidak tau kenapa 

`def sale_change(self, cr, uid, ids, sale, loc):`

![untitled](https://cloud.githubusercontent.com/assets/5061661/13003567/da49884c-d1a8-11e5-82fa-83b985b73639.png)

**Comment by ekachandrasetiawan** [comment]
Sudah OK
