### ISSUE TITLE
Filter OP

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Supra#44]
@ekachandrasetiawan #14 : tolong tambahin filter di OP
- [x] filter by state draft, approve, done, cancel

**Comment by ekachandrasetiawan** [comment]
OK, Sudah
Tadi ada sedikit masalah, karna search nya sudah ada di modul ad_order_preparation 
Ternyata harus di inherit di XML nya. 

Jadi sekarang sudah OK
