### ISSUE TITLE
Automatic follower

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Supra#49]
@ekachandrasetiawan : 

Bikin method _set_followers() di order preparation #14 

dimana method nya untuk mengeset follower

Set Follower untuk OP = Warehouse

**Comment by lajayuhniyarsyah** [comment]
@ekachandrasetiawan : 
method nya namain **_set_followers()**

**Comment by ekachandrasetiawan** [comment]
Sudah OK, untuk mendaftarkan user yang terkait d dalam group di followers OP

**Comment by lajayuhniyarsyah** [comment]
@ekachandrasetiawan : di pull donk
