### ISSUE TITLE
Notifikasi - OP

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Supra#51]
@ekachandrasetiawan : terkait issue #14 
- [ ]Add Notifikasi OP unread message

**Comment by ekachandrasetiawan** [comment]
1. Add Followers 
2. Search By unread message
3. Flag unread message untuk setiap user yang telah difollow 
4. merubah status menjadi unread message kembali, dalam action confirm dan validate

**Comment by lajayuhniyarsyah** [comment]
@ekachandrasetiawan : 
_set_message_unread dan _set_mail_notification untuk set unread dan notif per group admin_ho ya ??

**Comment by ekachandrasetiawan** [comment]
Iya..
untuk Notification bahwa doc belum dilihat oleh user di group admin HO. 

apakah sudah benar?
untuk notif angka di menu item belum dapat dilakukan, belum tau caranya.

tapi secara data telah benar di object mail.notification

**Comment by ekachandrasetiawan** [comment]
sudah di coba dan sudah OK, 
1. Notification ke Message Inbox setiap user yang telah di follow
2. Menghilangkan post message 
3. Mengirim notification di setiap perubahan state doc kepada user yang ter follow
