### ISSUE TITLE
Butuh Print Out web Interface untuk Purchase Order Import

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Supra#52]
@ekachandrasetiawan : 
Karena beragam masalah dalam print out Purchase Order Import,, dirasa perlu untuk mengganti modul nya ke format web print
- [ ]

**Comment by lajayuhniyarsyah** [comment]
@ekachandrasetiawan : 
Coba print 019 J / INDENT / II / 2016
masih belum sesuai dengan pdf

**Comment by lajayuhniyarsyah** [comment]
@ekachandrasetiawan  : 
Ketika print 019 J ada 6 halaman,, halaman 1 ok
halaman terakhir ok
halaman 2-5 pasti print nya over,, karena print menggunakan kop surat

**Comment by ekachandrasetiawan** [comment]
Sudah OK 

File GIT 
https://github.com/lajayuhniyarsyah/OpenPrint/commit/691bd1f06bb64553c50a36f99aa3c46b56f1e7d1

Mohon dapat di check kembali

**Comment by lajayuhniyarsyah** [comment]
Ok Close
