### ISSUE TITLE
RFQ Filter

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Supra#57]
@Mohammadrezafah : di RFQ filternya kurang,,, harus bisa filter / mencari berdasarkan quotation_no dan name (Sale Order No)
#19

**Comment by lajayuhniyarsyah** [comment]
@Mohammadrezafah : ini commit nya yang mana ya ??

**Comment by Mohammadrezafah** [comment]
ini mas jay b05c881f8dc464e361d450e4d66207dd3bc9b3ab

**Comment by Mohammadrezafah** [comment]
b05c881f8dc464e361d450e4d66207dd3bc9b3ab
