### ISSUE TITLE
wizard win quotation

### ISSUE THREAD

**Issue by Mohammadrezafah** [lajayuhniyarsyah/ERP-Supra#6]
@lajayuhniyarsyah 

http://snag.gy/OptNx.jpg

sale_order_id itu dari objek mana ? klo misal dari wizard_win_quatation itu tidak ada .

terimakasih

**Comment by lajayuhniyarsyah** [comment]
@Mohammadrezafah  itu di process ada

sale_order_id = context[active_id]

**Comment by Mohammadrezafah** [comment]
@lajayuhniyarsyah 

ngambil data sale_order_id dari self.browse ?
