### ISSUE TITLE
BUG - Delivery Note - Stock Move

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Supra#62]
Ketika Pembentukan picking di delivery note
di stock move ada beberapa field yang belum tercopy datannya
- [x] field name di stock_move diisi dengan description di delivery note material
  ![Image stock move name](http://snag.gy/Bi0tS.jpg)
#18

**Comment by ekachandrasetiawan** [comment]
Apakah dibuat Kondisi jika Desc di Material Line Kosong agar mengisi name dari master Product ?

**Comment by lajayuhniyarsyah** [comment]
Tidak usah,,, product nya sudah ada jadi ga repeat data

**Comment by ekachandrasetiawan** [comment]
SUDAH OK

**Comment by lajayuhniyarsyah** [comment]
pull request
