### ISSUE TITLE
Bug Delivery Note - Return View Modal

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Supra#64]
Pada saat return dari DN kita akan langsung di redirect ke Form stock.picking.in seperti gambar 1
![Gambar 1](http://snag.gy/emOFq.jpg)

Ketika Halaman di refresh (F5) lalu buka DN tersebut kembali maka kita buka data return di tab "Process Retur". Di tab tersebut ada list tabel return,, ketika buka data retur akan muncul "Modal Dialog Stock Picking"
![Gambar 2](http://snag.gy/NVMB7.jpg)

Perbedaannya adalah : 
- Jika di receive melalui form kasus 1 maka diwajibkan mengisi field "Ext Doc Ref"
- JIka di receive melalui form kasus ke 2 maka field "Ext Doc Ref" boleh kosong,,
- [x]  Field **Ext Doc Ref** harus diisi

**Comment by ekachandrasetiawan** [comment]
SUDAH OK

**Comment by lajayuhniyarsyah** [comment]
pull request
