### ISSUE TITLE
On change Sale Man

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Supra#74]
Di form adhoc order field sales_man_id dikasih on_change memilih sales_group_id
#60

**Comment by ekachandrasetiawan** [comment]
Sudah OK

**Comment by lajayuhniyarsyah** [comment]
@ekachandrasetiawan : 

``` python
res = {'value':{'sale_group_id':s_man.kelompok_id.id}}
```

struktur group sekarang

Main Group 1
- Child 1 1
- Child 1 2

Main Group 2
- Child 2 1
- Child 2 2

Data USer : 
User "A" -> kelompok_id = Child 1 1

Dilihat dari data user maka seharusnya 
ID yang di return adalah id Main Group nya / parent nya

**Comment by lajayuhniyarsyah** [comment]
di cek aja jika kelompok_id ada parent nya maka return nya pake parent_id nya
