### ISSUE TITLE
Create PB on Sale Order

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Supra#78]
#19

Di form sale order ada button "**Create PB**"
Button tersebut merupakan button wizard untuk membuat dokumen regular.requisition

Di modul existing Create PB berdasarkan item SO Line
Dikarenakan dengan modul so material line maka PB harus dibuat / ditarik dari item SO Material Line

**Comment by lajayuhniyarsyah** [comment]
@Mohammadrezafah : di wizard tambahin dfield sale_order_material_line_id

dan di object **detail.pb** tambahin field sale_order_material_line_id dimana field jenis many2one ke object sale.order.material.line

**Comment by Mohammadrezafah** [comment]
89f396223eb2f1a491fff16391c6e5d7c06b6544
