### ISSUE TITLE
Group di use case tidak muncul Menu Work Order

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Supra#79]
Group Admin HO tidak munul menu "Work Order" dan anak nya yaitu adhoc order dan work order
#59

**Comment by lajayuhniyarsyah** [comment]
@ekachandrasetiawan : ternyata semua group yang ada di use case seperti #59 tidak muncul menu tersebut

**Comment by ekachandrasetiawan** [comment]
Sudah OK

**Comment by lajayuhniyarsyah** [comment]
Ok Pull request Can

**Comment by lajayuhniyarsyah** [comment]
@ekachandrasetiawan : pakai group admin support yang sudah ada jadi jangan create baru
