### ISSUE TITLE
Sale Order Material Delivery Tracking

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Supra#81]
Buat report sale order material Delivery Tracking

di file excel ada tab SO Material Delivery Tracking
[report.xlsx](https://github.com/lajayuhniyarsyah/ERP-Supra/files/156289/report.xlsx)

**Comment by Mohammadrezafah** [comment]
29079b98b83f4ff7beffe1ee1845784b57042714 ini xml nya
786f4c220eac33d3997ea78a6db2c491a0dae28c ini buat penambahan field related ke so

**Comment by lajayuhniyarsyah** [comment]
:+1:

**Comment by lajayuhniyarsyah** [comment]
Pull request

**Comment by lajayuhniyarsyah** [comment]
@Mohammadrezafah : 
Issue di open ya

masih ada task 
- [ ] Tanggal order
- [ ] Due Date

**Comment by lajayuhniyarsyah** [comment]
@Mohammadrezafah : 

Untuk detail form tolong ditambah feature 
- [ ] List Order Preparation Line nya Dan Surat Jalan nya yang sudah terbentuk apa saja
