### ISSUE TITLE
Rules  - SPK

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Supra#88]
Perlu aturan Rule akses data SPK
- Admin HO / Admin Supervisor / Admin Manager: 
  - Dapat Melihat Seluruh SPK
- Admin Support : 
  - Hanya dapat melihat SPK yang dia buat / user nya terdaftar di follower nya
#59

**Comment by ekachandrasetiawan** [comment]
Sudah OK
