### ISSUE TITLE
Bug Duplicate Tarik SPK dari SO

### ISSUE THREAD

**Issue by lajayuhniyarsyah** [lajayuhniyarsyah/ERP-Supra#96]
Case : 

SO sudah pernah di tarik ke SPK
ketika di tarik SPK baru seharusnya tidak bisa

Harus dibuat sistem perhitungan untuk dapat menghitung sisa qty yang belum terproses SPK / sisa material yang belum terproses SPK
#59

**Comment by ekachandrasetiawan** [comment]
Menghitung nya dari kondisi apa ?

**Comment by lajayuhniyarsyah** [comment]
Di SPK output ada field sale_order_material

On change sale_order_id pada saat loop sale order material bisa di cek berpa qty yang sudah di tarik ke spk yang berstatus bukan cancel.

**Comment by ekachandrasetiawan** [comment]
Sudah OK
